/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as RebuyRouteImport } from './routes/rebuy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as NewMonthRouteImport } from './routes/new-month'
import { Route as MealsRouteImport } from './routes/meals'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as HouseholdRouteImport } from './routes/household'
import { Route as ExpiringRouteImport } from './routes/expiring'
import { Route as BulkRouteImport } from './routes/bulk'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory.index'
import { Route as InventoryIdRouteImport } from './routes/inventory.$id'

const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const RebuyRoute = RebuyRouteImport.update({
  id: '/rebuy',
  path: '/rebuy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const NewMonthRoute = NewMonthRouteImport.update({
  id: '/new-month',
  path: '/new-month',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsRoute = MealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdRoute = HouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpiringRoute = ExpiringRouteImport.update({
  id: '/expiring',
  path: '/expiring',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkRoute = BulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIdRoute = InventoryIdRouteImport.update({
  id: '/inventory/$id',
  path: '/inventory/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/budget': typeof BudgetRoute
  '/bulk': typeof BulkRoute
  '/expiring': typeof ExpiringRoute
  '/household': typeof HouseholdRoute
  '/insights': typeof InsightsRoute
  '/meals': typeof MealsRoute
  '/new-month': typeof NewMonthRoute
  '/predictions': typeof PredictionsRoute
  '/privacy': typeof PrivacyRoute
  '/rebuy': typeof RebuyRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/shopping': typeof ShoppingRoute
  '/voice': typeof VoiceRoute
  '/inventory/$id': typeof InventoryIdRoute
  '/inventory/': typeof InventoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/budget': typeof BudgetRoute
  '/bulk': typeof BulkRoute
  '/expiring': typeof ExpiringRoute
  '/household': typeof HouseholdRoute
  '/insights': typeof InsightsRoute
  '/meals': typeof MealsRoute
  '/new-month': typeof NewMonthRoute
  '/predictions': typeof PredictionsRoute
  '/privacy': typeof PrivacyRoute
  '/rebuy': typeof RebuyRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/shopping': typeof ShoppingRoute
  '/voice': typeof VoiceRoute
  '/inventory/$id': typeof InventoryIdRoute
  '/inventory': typeof InventoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/budget': typeof BudgetRoute
  '/bulk': typeof BulkRoute
  '/expiring': typeof ExpiringRoute
  '/household': typeof HouseholdRoute
  '/insights': typeof InsightsRoute
  '/meals': typeof MealsRoute
  '/new-month': typeof NewMonthRoute
  '/predictions': typeof PredictionsRoute
  '/privacy': typeof PrivacyRoute
  '/rebuy': typeof RebuyRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/shopping': typeof ShoppingRoute
  '/voice': typeof VoiceRoute
  '/inventory/$id': typeof InventoryIdRoute
  '/inventory/': typeof InventoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/budget'
    | '/bulk'
    | '/expiring'
    | '/household'
    | '/insights'
    | '/meals'
    | '/new-month'
    | '/predictions'
    | '/privacy'
    | '/rebuy'
    | '/scan'
    | '/settings'
    | '/shopping'
    | '/voice'
    | '/inventory/$id'
    | '/inventory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/budget'
    | '/bulk'
    | '/expiring'
    | '/household'
    | '/insights'
    | '/meals'
    | '/new-month'
    | '/predictions'
    | '/privacy'
    | '/rebuy'
    | '/scan'
    | '/settings'
    | '/shopping'
    | '/voice'
    | '/inventory/$id'
    | '/inventory'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/budget'
    | '/bulk'
    | '/expiring'
    | '/household'
    | '/insights'
    | '/meals'
    | '/new-month'
    | '/predictions'
    | '/privacy'
    | '/rebuy'
    | '/scan'
    | '/settings'
    | '/shopping'
    | '/voice'
    | '/inventory/$id'
    | '/inventory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  BudgetRoute: typeof BudgetRoute
  BulkRoute: typeof BulkRoute
  ExpiringRoute: typeof ExpiringRoute
  HouseholdRoute: typeof HouseholdRoute
  InsightsRoute: typeof InsightsRoute
  MealsRoute: typeof MealsRoute
  NewMonthRoute: typeof NewMonthRoute
  PredictionsRoute: typeof PredictionsRoute
  PrivacyRoute: typeof PrivacyRoute
  RebuyRoute: typeof RebuyRoute
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  ShoppingRoute: typeof ShoppingRoute
  VoiceRoute: typeof VoiceRoute
  InventoryIdRoute: typeof InventoryIdRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rebuy': {
      id: '/rebuy'
      path: '/rebuy'
      fullPath: '/rebuy'
      preLoaderRoute: typeof RebuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-month': {
      id: '/new-month'
      path: '/new-month'
      fullPath: '/new-month'
      preLoaderRoute: typeof NewMonthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals': {
      id: '/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof MealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/household': {
      id: '/household'
      path: '/household'
      fullPath: '/household'
      preLoaderRoute: typeof HouseholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expiring': {
      id: '/expiring'
      path: '/expiring'
      fullPath: '/expiring'
      preLoaderRoute: typeof ExpiringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk': {
      id: '/bulk'
      path: '/bulk'
      fullPath: '/bulk'
      preLoaderRoute: typeof BulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/$id': {
      id: '/inventory/$id'
      path: '/inventory/$id'
      fullPath: '/inventory/$id'
      preLoaderRoute: typeof InventoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  BudgetRoute: BudgetRoute,
  BulkRoute: BulkRoute,
  ExpiringRoute: ExpiringRoute,
  HouseholdRoute: HouseholdRoute,
  InsightsRoute: InsightsRoute,
  MealsRoute: MealsRoute,
  NewMonthRoute: NewMonthRoute,
  PredictionsRoute: PredictionsRoute,
  PrivacyRoute: PrivacyRoute,
  RebuyRoute: RebuyRoute,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  ShoppingRoute: ShoppingRoute,
  VoiceRoute: VoiceRoute,
  InventoryIdRoute: InventoryIdRoute,
  InventoryIndexRoute: InventoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
